version: '2'

services:
  web:
    image: oiwifi/chicken-dad-backend
    links:
      - db
    env_file: .web.env
    networks:
      - front-tier
      - back-tier
  db:
    image: postgres:9.4
    env_file: .db.env
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: